### ISSUE TITLE
Missing file hparams.json for evaluation

### ISSUE THREAD

**Issue by giuseppecartella** [chenxy99/GazeXplain#2]
Hi @chenxy99 ,

I was running your code for testing but I noticed that the file hparams.json seems to be missing and it is not present in the ALL_runX_baseline folder. Only the checkpoint folder is present.

I would appreciate if you can add the file.
Thanks,
Giuseppe

**Comment by chenxy99** [comment]
Hello Giuseppe,

I have added the `hparams.json` file to the pretrained model. You can try downloading it again. I also made a small change in the code that allows you to specify your `dataset_dir`.

I hope this resolves your issue. If you have any further questions, please feel free to contact me.

Best regards,
Xianyu
